name: Build and deploy container

on:
  push:
    branches:
      - main
    paths-ignore:
      - ".devcontainer/**"
      - ".github/**"
      - "README.md"
      - "LICENSE"
  schedule:
    - cron: "12 3 * * 0"
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  configure-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v5
      - uses: docker/bake-action/subaction/matrix@v6
        id: generate-matrix
        with:
          files: docker-bake.hcl
          target: default

    outputs:
      matrix: ${{ steps.generate-matrix.outputs.targets }}

  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    needs:
